project_id = "mhtikjiticopicziepnj"

[functions.verify-acceptance]
verify_jwt = false

[functions.forfeit-game]
verify_jwt = false

[functions.recover-funds]
verify_jwt = false

[functions.settle-draw]
verify_jwt = false

[functions.set-manual-starter]
verify_jwt = false

[functions.submit-move]
verify_jwt = false

[functions.get-moves]
verify_jwt = false
